# Generated by Django 5.0.1 on 2024-02-21 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Название')),
                ('address', models.TextField(unique=True, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Корпус',
                'verbose_name_plural': 'Корпуса',
            },
        ),
        migrations.CreateModel(
            name='CodeDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код направления')),
                ('name', models.TextField(unique=True, verbose_name='Наименование направления')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
            },
        ),
        migrations.CreateModel(
            name='Disciplines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название дисциплины')),
            ],
            options={
                'verbose_name': 'Дисциплину',
                'verbose_name_plural': 'Дисциплины',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Группу',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Pairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Номер пары')),
                ('time_start', models.TimeField(verbose_name='Время начала')),
                ('time_end', models.TimeField(verbose_name='Время окончания')),
            ],
            options={
                'verbose_name': 'Пару',
                'verbose_name_plural': 'Пары',
            },
        ),
        migrations.CreateModel(
            name='Prepods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(default='', max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Имя')),
                ('patronymic', models.CharField(default='', max_length=50, null=True, verbose_name='Отчество')),
                ('education', models.TextField(default='', null=True, verbose_name='Образование')),
                ('qualification', models.TextField(default='', null=True, verbose_name='Данные о повышении квалификации')),
                ('post', models.TextField(default='преподаватель', max_length=300, verbose_name='Должность')),
                ('disciplines', models.TextField(default='', verbose_name='Преподаваемые дисциплины')),
                ('full_expirience', models.CharField(default='', max_length=150, null=True, verbose_name='Общий трудовой стаж')),
                ('prepod_expirience', models.CharField(default='', max_length=150, null=True, verbose_name='Педагогический стаж')),
                ('sharaga_expirience', models.CharField(default='', max_length=150, null=True, verbose_name='Стаж работы в техникуме')),
                ('contacts', models.TextField(default='', null=True, verbose_name='Контакты')),
                ('degree', models.TextField(default='нет/нет', verbose_name='Ученая степень/категория')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience_number', models.CharField(default='', max_length=10, null=True, verbose_name='Номер аудитории')),
                ('date', models.DateField(default='', null=True, verbose_name='Дата')),
                ('building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mptsite.building', verbose_name='Корпус')),
                ('discipline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mptsite.disciplines')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mptsite.group', verbose_name='Группа')),
                ('number_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mptsite.pairs', verbose_name='Номер пары')),
                ('prepod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mptsite.prepods', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Строку расписания',
                'verbose_name_plural': 'Расписание',
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mptsite.codedirection', verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mptsite.speciality'),
        ),
    ]
