# Generated by Django 5.0.1 on 2024-05-07 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Название')),
                ('address', models.TextField(unique=True, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Корпус',
                'verbose_name_plural': 'Корпуса',
            },
        ),
        migrations.CreateModel(
            name='Category_of_questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='Наименование категории')),
            ],
            options={
                'verbose_name': 'Категория вопроса',
                'verbose_name_plural': 'Категории вопросов',
            },
        ),
        migrations.CreateModel(
            name='CodeDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код направления')),
                ('name', models.TextField(unique=True, verbose_name='Наименование направления')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
            },
        ),
        migrations.CreateModel(
            name='DateTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название блока')),
                ('date_from', models.DateField(verbose_name='Начало блока')),
                ('date_end', models.DateField(verbose_name='Конец блока')),
            ],
            options={
                'verbose_name': 'Блок расписания',
                'verbose_name_plural': 'Блоки расписания',
            },
        ),
        migrations.CreateModel(
            name='Disciplines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название дисциплины')),
            ],
            options={
                'verbose_name': 'Дисциплину',
                'verbose_name_plural': 'Дисциплины',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Группу',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата новости')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(default='', null=True, verbose_name='Содержимое новости')),
                ('link', models.URLField(null=True, verbose_name='Ссылка на подробную запись')),
                ('picture', models.ImageField(null=True, upload_to='server/static/mptsite/img/news', verbose_name='Превью-картинка')),
                ('short_description', models.CharField(default='', max_length=100, verbose_name='Краткое описание')),
                ('date_to', models.DateField(verbose_name='Актуально до')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Pairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Номер пары')),
                ('time_start', models.TimeField(verbose_name='Время начала')),
                ('time_end', models.TimeField(verbose_name='Время окончания')),
            ],
            options={
                'verbose_name': 'Пару',
                'verbose_name_plural': 'Пары',
            },
        ),
        migrations.CreateModel(
            name='Prepods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(default='', max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Имя')),
                ('patronymic', models.CharField(default='', max_length=50, null=True, verbose_name='Отчество')),
                ('education', models.TextField(default='', null=True, verbose_name='Образование')),
                ('qualification', models.TextField(default='', null=True, verbose_name='Данные о повышении квалификации')),
                ('post', models.TextField(default='преподаватель', max_length=300, verbose_name='Должность')),
                ('disciplines', models.TextField(default='', verbose_name='Преподаваемые дисциплины')),
                ('full_expirience', models.CharField(default='', max_length=150, null=True, verbose_name='Общий трудовой стаж')),
                ('prepod_expirience', models.CharField(default='', max_length=150, null=True, verbose_name='Педагогический стаж')),
                ('sharaga_expirience', models.CharField(default='', max_length=150, null=True, verbose_name='Стаж работы в техникуме')),
                ('contacts', models.TextField(default='', null=True, verbose_name='Контакты')),
                ('degree', models.TextField(default='нет/нет', verbose_name='Ученая степень/категория')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mptsite.category_of_questions', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience_number', models.CharField(default='', max_length=10, null=True, verbose_name='Номер аудитории')),
                ('date', models.DateField(default='', null=True, verbose_name='Дата')),
                ('ischange', models.BooleanField(default=False, verbose_name='Замена?')),
                ('iscanceled', models.BooleanField(default=False, verbose_name='Отмена?')),
                ('isdistance', models.BooleanField(default=False, verbose_name='Дистант?')),
                ('block_rasp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mptsite.datetemplates', verbose_name='Блок расписания')),
                ('building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mptsite.building', verbose_name='Корпус')),
                ('discipline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mptsite.disciplines')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mptsite.group', verbose_name='Группа')),
                ('number_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mptsite.pairs', verbose_name='Номер пары')),
                ('prepod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mptsite.prepods', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Строку расписания',
                'verbose_name_plural': 'Расписание',
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mptsite.codedirection', verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mptsite.speciality'),
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=256, unique=True, verbose_name='Токен доступа')),
                ('secret_user', models.CharField(max_length=256, unique=True, verbose_name='Секрет пользователя')),
                ('sex', models.BooleanField(default=False, verbose_name='Мужчина?')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mptsite.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.AddConstraint(
            model_name='schedules',
            constraint=models.UniqueConstraint(fields=('date', 'group', 'discipline', 'number_pair', 'prepod', 'ischange'), name='unique_schedul_string'),
        ),
    ]
