# Generated by Django 5.0.1 on 2024-02-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('Name', models.CharField(max_length=20, verbose_name='Имя')),
                ('Patronymic', models.CharField(default='', max_length=30, null=True, verbose_name='Отчество')),
                ('Education', models.TextField(verbose_name='Образование')),
                ('Qualification', models.TextField(default='', null=True, verbose_name='Данные о повышении квалификации')),
                ('Post', models.CharField(max_length=100, verbose_name='Должность')),
                ('Disciplines', models.CharField(max_length=100, verbose_name='Преподаваемые дисциплины')),
                ('Full_expirience', models.IntegerField(verbose_name='Общий трудовой стаж')),
                ('Prepod_expirience', models.IntegerField(verbose_name='Педагогический стаж')),
                ('Sharaga_expirience', models.IntegerField(verbose_name='Стаж работы в техникуме')),
                ('Contacts', models.EmailField(default='', max_length=254, null=True, verbose_name='Контакты')),
                ('Degree', models.TextField(default='нет', max_length=50, verbose_name='Ученая степень\\категория')),
            ],
        ),
    ]
