# Generated by Django 5.0.1 on 2024-02-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mptsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название блока')),
                ('date_from', models.DateField(verbose_name='Начало блока')),
                ('date_end', models.DateField(verbose_name='Конец блока')),
            ],
            options={
                'verbose_name': 'Блок расписания',
                'verbose_name_plural': 'Блоки расписания',
            },
        ),
    ]
