# Generated by Django 5.0.1 on 2024-02-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mptsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='date',
            field=models.DateField(default='', null=True, verbose_name='Дата'),
        ),
    ]
