# Generated by Django 5.0.1 on 2024-02-05 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mptsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
    ]
