# Generated by Django 5.0.1 on 2024-05-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mptsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Specialities',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name='Полное название'),
        ),
    ]
