# Generated by Django 5.0.1 on 2024-02-21 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mptsite', '0002_datetemplates'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedules',
            name='block_rasp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mptsite.datetemplates', verbose_name='Блок расписания'),
        ),
    ]
