# Generated by Django 5.0.1 on 2024-02-05 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mptsite', '0002_alter_teacher_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('address', models.TextField(verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Корпус',
                'verbose_name_plural': 'Корпуса',
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Код направления')),
                ('name', models.TextField(verbose_name='Наименование направления')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
            },
        ),
        migrations.CreateModel(
            name='Disciplines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название дисциплины')),
            ],
            options={
                'verbose_name': 'Дисциплину',
                'verbose_name_plural': 'Дисциплины',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('directions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mptsite.direction')),
            ],
            options={
                'verbose_name': 'Группу',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Pairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер пары')),
                ('time_start', models.TimeField(verbose_name='Время начала')),
                ('time_end', models.TimeField(verbose_name='Время оконччания')),
            ],
            options={
                'verbose_name': 'Пару',
                'verbose_name_plural': 'Пары',
            },
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience_number', models.CharField(max_length=10, verbose_name='Номер аудитории')),
                ('date', models.DateField(verbose_name='Дата')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mptsite.building', verbose_name='Корпус')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mptsite.disciplines')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mptsite.group', verbose_name='Группа')),
                ('number_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mptsite.pairs', verbose_name='Номер пары')),
            ],
            options={
                'verbose_name': 'Строку расписания',
                'verbose_name_plural': 'Расписание',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('patronymic', models.CharField(default='', max_length=30, null=True, verbose_name='Отчество')),
                ('education', models.TextField(verbose_name='Образование')),
                ('kvalificationsUp', models.TextField(verbose_name='Данные о повышении квалификации')),
                ('post', models.CharField(max_length=100, verbose_name='Должность')),
                ('disciplins', models.TextField(verbose_name='Преподаваемые дисциплины')),
                ('workTime', models.IntegerField(verbose_name='Общий трудовой стаж')),
                ('studyTime', models.IntegerField(verbose_name='Педагогический стаж')),
                ('techTtime', models.IntegerField(verbose_name='Стаж работы в техникуме')),
                ('degree', models.TextField(default='нет', verbose_name='Учёная степень')),
            ],
            options={
                'verbose_name': 'Преподавателя',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.AddField(
            model_name='schedules',
            name='prepod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mptsite.teachers', verbose_name='Преподаватель'),
        ),
    ]
