# Generated by Django 5.0.1 on 2024-02-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mptsite', '0002_alter_schedules_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='audience_number',
            field=models.CharField(default='', max_length=10, null=True, verbose_name='Номер аудитории'),
        ),
    ]
