# Generated by Django 5.0.1 on 2024-05-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mptsite', '0002_alter_specialities_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='course',
            field=models.IntegerField(default=2, verbose_name='Курс'),
        ),
    ]
