# Generated by Django 5.0.1 on 2024-02-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mptsite', '0003_schedules_block_rasp'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedules',
            name='ischange',
            field=models.BooleanField(default=False, verbose_name='Замена?'),
        ),
    ]
