# Generated by Django 5.0.1 on 2024-02-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mptsite', '0003_building_direction_disciplines_group_pairs_schedules_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplines',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название дисциплины'),
        ),
    ]
