# Generated by Django 5.0.1 on 2024-05-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mptsite', '0003_alter_groups_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='email',
            field=models.EmailField(default='', max_length=300, null=True, verbose_name='Почта'),
        ),
    ]
