# Generated by Django 5.0.3 on 2024-06-01 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mptsite', '0004_alter_employees_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedules',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Teacher_Disciplines',
        ),
    ]
