# Generated by Django 5.0.1 on 2024-05-31 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mptsite', '0004_alter_employees_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='is_cancel',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mptsite.pair_statuses', verbose_name='Отмена?'),
        ),
        migrations.AlterUniqueTogether(
            name='teacher_disciplines',
            unique_together={('discipline', 'employee')},
        ),
    ]
