# Generated by Django 5.0.1 on 2024-06-15 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mptsite', '0006_alter_employees_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_disciplines',
            name='employee',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mptsite.employees', verbose_name='Сотрудник'),
        ),
    ]
