# Generated by Django 5.0.1 on 2024-06-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mptsite', '0007_alter_teacher_disciplines_employee'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='teacher_disciplines',
            constraint=models.UniqueConstraint(fields=('discipline', 'employee'), name='Teacher_Disc_UQ'),
        ),
    ]
