# Generated by Django 4.2.14 on 2024-08-07 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mptsite', '0007_schedules_teacher'),
        ('mptsite', '0009_alter_teacher_disciplines_unique_together_and_more'),
    ]

    operations = [
    ]
