# Generated by Django 4.2.14 on 2024-08-07 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mptsite', '0010_merge_20240807_0404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher_disciplines',
            options={'verbose_name': 'Преподаваемую дисциплину', 'verbose_name_plural': 'Преподаваемые дисциплины'},
        ),
        migrations.RemoveField(
            model_name='disciplines',
            name='employees',
        ),
        migrations.AlterField(
            model_name='schedules',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mptsite.teacher_disciplines', verbose_name='Преподаватель'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher_disciplines',
            name='employee',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mptsite.employees', verbose_name='Сотрудник'),
        ),
        migrations.AddConstraint(
            model_name='teacher_disciplines',
            constraint=models.UniqueConstraint(fields=('discipline', 'employee'), name='Teacher_Disc_UQ'),
        ),
        migrations.AddConstraint(
            model_name='teacher_disciplines',
            constraint=models.UniqueConstraint(condition=models.Q(('employee', None)), fields=('discipline',), name='Teacher_Null_Disc_UQ'),
        ),
    ]
