# Generated by Django 5.0.1 on 2024-08-20 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Название')),
                ('address', models.TextField(unique=True, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Здание',
                'verbose_name_plural': 'Здания',
            },
        ),
        migrations.CreateModel(
            name='Category_of_questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='Наименование блока')),
            ],
            options={
                'verbose_name': 'Блок вопросов',
                'verbose_name_plural': 'Блоки вопросов',
            },
        ),
        migrations.CreateModel(
            name='DateTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Название статуса')),
                ('date_from', models.DateField(verbose_name='Блок с')),
                ('date_end', models.DateField(verbose_name='Блок по')),
            ],
            options={
                'verbose_name': 'Блок расписания',
                'verbose_name_plural': 'Блоки генерации расписания',
            },
        ),
        migrations.CreateModel(
            name='Directions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=50, unique=True, verbose_name='Код направления')),
                ('name', models.TextField(unique=True, verbose_name='Название направления')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
            },
        ),
        migrations.CreateModel(
            name='Disciplines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline_name', models.CharField(max_length=200, unique=True, verbose_name='Название дисциплины')),
            ],
            options={
                'verbose_name': 'Дисциплину',
                'verbose_name_plural': 'Направления',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(default='', max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Имя')),
                ('patronymic', models.CharField(default='', max_length=50, null=True, verbose_name='Отчество')),
                ('education', models.TextField(default='', null=True, verbose_name='Образование')),
                ('qualification', models.TextField(default='', null=True, verbose_name='Квалификация')),
                ('post', models.CharField(default='', max_length=300, null=True, verbose_name='Должность')),
                ('total_work_experience', models.TextField(default='', null=True, verbose_name='Общий стаж работы')),
                ('teaching_work_experience', models.TextField(default='', null=True, verbose_name='Педагогический стаж')),
                ('teaching_work_experience_MPT', models.TextField(default='', null=True, verbose_name='Стаж рабооты в техникуме')),
                ('phone', models.CharField(default='', max_length=20, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(default='', max_length=300, null=True, verbose_name='Почта')),
                ('degree', models.TextField(default='', null=True, verbose_name='Ученая степень')),
            ],
            options={
                'verbose_name': 'Работника',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата новости')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(default='', null=True, verbose_name='Содержимое новости')),
                ('link', models.URLField(null=True, verbose_name='Ссылка на подробную запись')),
                ('picture', models.ImageField(null=True, upload_to='news/', verbose_name='Превью-картинка')),
                ('short_description', models.TextField(default='', max_length=100, verbose_name='Краткое описание')),
                ('date_to', models.DateField(verbose_name='Актуально до')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Pair_numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.CharField(max_length=20, verbose_name='Начало пары')),
                ('time_finish', models.CharField(max_length=20, verbose_name='Конец пары')),
            ],
            options={
                'verbose_name': 'Время пары',
                'verbose_name_plural': 'Время пары',
            },
        ),
        migrations.CreateModel(
            name='Pair_statuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Название статуса')),
            ],
            options={
                'verbose_name': 'Статус пары',
                'verbose_name_plural': 'Статусы пар',
            },
        ),
        migrations.CreateModel(
            name='Subcategory_of_questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=100, verbose_name='Наименование подкатегории')),
            ],
            options={
                'verbose_name': 'Подкатегория вопроса',
                'verbose_name_plural': 'Подкатегории вопросов',
            },
        ),
        migrations.CreateModel(
            name='Specialities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=10, verbose_name='Краткое название')),
                ('full_name', models.CharField(max_length=150, verbose_name='Полное название')),
                ('base_on_9', models.BooleanField(default=False, verbose_name='На базе 9-го')),
                ('base_on_11', models.BooleanField(default=False, verbose_name='На базе 11-го')),
                ('description', models.TextField(default='', verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна для набора')),
                ('direction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mptsite.directions', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50, unique=True, verbose_name='Название группы')),
                ('course', models.IntegerField(default=2, verbose_name='Курс')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mptsite.specialities', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Группу',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Disciplines_Specialities_Hours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_amount', models.PositiveIntegerField(default=0, null=True, verbose_name='Время по рабочему плану')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mptsite.disciplines', verbose_name='Дисциплина')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mptsite.specialities', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Количество часов',
                'verbose_name_plural': 'Количества часов',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mptsite.category_of_questions', verbose_name='Блок для расположения')),
                ('subcategory_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mptsite.subcategory_of_questions', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Teacher_Disciplines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mptsite.disciplines', verbose_name='Дисциплина')),
                ('employee', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mptsite.employees', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Преподаваемую дисциплину',
                'verbose_name_plural': 'Преподаваемые дисциплины',
            },
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(default='', max_length=10, null=True, verbose_name='Аудитория')),
                ('date', models.DateField(null=True, verbose_name='Дата проведения')),
                ('is_change', models.BooleanField(default=False, verbose_name='Является заменой?')),
                ('is_remote', models.BooleanField(default=False, verbose_name='Дистанционно?')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mptsite.buildings', verbose_name='Корпус')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mptsite.groups', verbose_name='Группа')),
                ('is_cancel', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mptsite.pair_statuses', verbose_name='Отмена?')),
                ('pair_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mptsite.pair_numbers', verbose_name='Номер пары')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mptsite.teacher_disciplines', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Пара',
                'verbose_name_plural': 'Пары',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=256, unique=True, verbose_name='Токен доступа')),
                ('secret_user', models.CharField(max_length=256, unique=True, verbose_name='Секрет пользователя')),
                ('sex', models.BooleanField(default=False, verbose_name='Мужчина?')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mptsite.groups', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.AddConstraint(
            model_name='teacher_disciplines',
            constraint=models.UniqueConstraint(fields=('discipline', 'employee'), name='Teacher_Disc_UQ'),
        ),
        migrations.AddConstraint(
            model_name='teacher_disciplines',
            constraint=models.UniqueConstraint(condition=models.Q(('employee', None)), fields=('discipline',), name='Teacher_Null_Disc_UQ'),
        ),
    ]
