# Generated by Django 5.0.1 on 2024-08-20 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mptsite', '0003_alter_news_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplines',
            options={'verbose_name': 'Дисциплину', 'verbose_name_plural': 'Дисциплины'},
        ),
    ]
